# Generated by Django 5.0 on 2024-01-25 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
        ("main", "0003_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Rdv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(default="null", max_length=255)),
                ("prenom", models.CharField(default="null", max_length=255)),
                ("telephone", models.CharField(blank=True, max_length=12)),
                ("heure", models.TimeField(default="00:00")),
                ("jour", models.DateField()),
                ("sujet", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "avocat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.avocat"
                    ),
                ),
            ],
        ),
    ]
