# Generated by Django 5.0 on 2024-01-04 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0003_avocat_lien_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(max_length=255)),
                ('avocat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat')),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentification.client')),
            ],
        ),
    ]
