# Generated by Django 5.0 on 2024-01-04 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentification', '0003_avocat_lien_localisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='null', max_length=255)),
                ('prenom', models.CharField(default='null', max_length=255)),
                ('email', models.EmailField(default='default@example.com', max_length=255)),
                ('heure', models.TimeField(default='00:00')),
                ('jour', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=255, null=True)),
                ('avocat', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat')),
            ],
        ),
    ]
