# Generated by Django 5.0 on 2024-01-04 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_avocat_lien_localisation'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdv',
            name='avocat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentification.avocat'),
        ),
    ]
