# Generated by Django 5.0 on 2024-01-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_rdv_avocat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='lieu',
            new_name='sujet',
        ),
        migrations.RemoveField(
            model_name='rdv',
            name='email',
        ),
        migrations.AddField(
            model_name='rdv',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
