# Generated by Django 5.0 on 2024-01-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_rename_lieu_rdv_sujet_remove_rdv_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='numero_telephone',
            new_name='numerotelephone',
        ),
    ]
