# Generated by Django 5.0 on 2024-01-24 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_rename_numero_telephone_rdv_numerotelephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rdv',
            old_name='numerotelephone',
            new_name='telephone',
        ),
    ]
