# Generated by Django 5.0 on 2023-12-29 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Avocat",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("nom", models.CharField(blank=True, max_length=255)),
                ("prenom", models.CharField(blank=True, max_length=255)),
                ("specialite", models.CharField(max_length=45, null=True)),
                ("telephone", models.CharField(blank=True, max_length=12)),
                ("adresse", models.CharField(blank=True, max_length=256)),
                ("tarif", models.FloatField()),
                ("evaluation", models.IntegerField(default=0)),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default="utilisateur.jpg",
                        max_length=256,
                        null=True,
                        upload_to="utilisateurs/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
