# Generated by Django 5.0 on 2024-01-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentification", "0002_admin_avocat_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="avocat",
            name="bio",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
