# Generated by Django 5.0.1 on 2024-01-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('registration_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='avocat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('prenom', models.CharField(blank=True, max_length=255)),
                ('specialite', models.CharField(max_length=45, null=True)),
                ('telephone', models.CharField(blank=True, max_length=12)),
                ('adresse', models.CharField(blank=True, max_length=256)),
                ('nbrvotes', models.IntegerField(default=0)),
                ('evaluation', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default='utilisateur.jpg', max_length=256, null=True, upload_to='utilisateurs/')),
                ('bio', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('registration_method', models.CharField(choices=[('email', 'Email'), ('google', 'Google')], default='email', max_length=10)),
            ],
        ),
    ]
