# Generated by Django 5.0 on 2024-01-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="registration_method",
            field=models.CharField(
                choices=[("email", "Email"), ("google", "Google")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="username",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
