# Generated by Django 5.0 on 2023-12-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avocat",
            name="photo",
            field=models.ImageField(upload_to="utilisateurs/"),
        ),
    ]
