# Generated by Django 5.0 on 2024-01-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_client_registration_method_client_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                ("email", models.CharField(max_length=250, unique=True)),
                (
                    "registration_method",
                    models.CharField(
                        choices=[("email", "Email"), ("google", "Google")],
                        default="email",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
