# Generated by Django 5.0 on 2024-01-03 11:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_avocat_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avocat",
            name="tarif",
        ),
    ]
