# Generated by Django 5.0 on 2023-12-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_avocat_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avocat",
            name="photo",
            field=models.ImageField(
                default="utilisateurs/utilisateur.jpg", upload_to="utilisateurs/"
            ),
        ),
    ]
