# Generated by Django 5.0 on 2023-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_avocat_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avocat",
            name="photo",
            field=models.CharField(
                blank=True, default="utilisateur.jpg", max_length=256, null=True
            ),
        ),
    ]
