# Generated by Django 5.0 on 2023-12-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_avocat_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avocat",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="utilisateur.jpg",
                max_length=256,
                null=True,
                upload_to="utilisateurs/",
            ),
        ),
    ]
