# Generated by Django 5.0 on 2024-01-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="avocat",
            name="nbrvotes",
            field=models.IntegerField(default=0),
        ),
    ]
