# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_inscription(self):
    self.driver.get("http://localhost:3000/inscription")
    self.driver.set_window_size(1296, 688)
    self.driver.find_element(By.ID, "nom").click()
    self.driver.find_element(By.ID, "nom").send_keys("Touati")
    self.driver.find_element(By.ID, "prenom").click()
    self.driver.find_element(By.ID, "prenom").send_keys("Rachid")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Touati_r")
    self.driver.find_element(By.ID, "adresse").click()
    self.driver.find_element(By.ID, "adresse").send_keys("Ben Aknoun Alger")
    self.driver.find_element(By.ID, "telephone").click()
    self.driver.find_element(By.ID, "telephone").send_keys("0553575463")
    self.driver.find_element(By.ID, "specialite").click()
    self.driver.find_element(By.ID, "specialite").send_keys("Droit des affaires")
    self.driver.find_element(By.ID, "photo").click()
    self.driver.find_element(By.ID, "photo").send_keys("C:\\fakepath\\Screenshot 2024-01-01 220927.png")
    self.driver.find_element(By.ID, "bio").click()
    self.driver.find_element(By.ID, "bio").send_keys("")
    self.driver.find_element(By.ID, "bio").click()
    element = self.driver.find_element(By.ID, "bio")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("rachid123")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("rachidtouati@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, ".checkbox").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("rachidtouati@gmail.com")
    self.driver.find_element(By.ID, "telephone").click()
    self.driver.find_element(By.ID, "telephone").send_keys("0553575463")
    self.driver.find_element(By.ID, "adresse").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("Touati_rn")
    self.driver.find_element(By.ID, "nom").click()
    self.driver.find_element(By.CSS_SELECTOR, ".button").click()
    assert self.driver.switch_to.alert.text == "Opération réussie !"
    assert self.driver.switch_to.alert.text == "Opération réussie !"
  
