# Generated by Django 5.0 on 2024-01-03 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_avocat_options_alter_avocat_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avocat',
            name='lien_localisation',
            field=models.URLField(blank=True, null=True),
        ),
    ]
