# Generated by Django 4.2.7 on 2023-12-08 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_client"),
        ("rendez", "0003_rdv"),
    ]

    operations = [
        migrations.AddField(
            model_name="rdv",
            name="client",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.client",
            ),
        ),
    ]
